-- Apply only the threat modeling tables if they don't exist

-- Create ThreatModels table
CREATE TABLE IF NOT EXISTS "ThreatModels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Asset" character varying(100) NOT NULL,
    "BusinessUnit" character varying(100) NOT NULL,
    "AssetOwner" character varying(100) NOT NULL,
    "AssetValue" numeric(18,2),
    "Status" integer NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "ApprovedBy" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ApprovedAt" timestamp with time zone,
    "NextReviewDate" timestamp with time zone,
    "ReviewNotes" text,
    "RiskAssessmentId" integer,
    CONSTRAINT "PK_ThreatModels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ThreatModels_RiskAssessments_RiskAssessmentId" FOREIGN KEY ("RiskAssessmentId") REFERENCES "RiskAssessments" ("Id") ON DELETE SET NULL
);

-- Create Attacks table
CREATE TABLE IF NOT EXISTS "Attacks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "KillChainPhase" integer NOT NULL,
    "AttackVector" integer NOT NULL,
    "AttackComplexity" integer NOT NULL,
    "ThreatActorType" integer NOT NULL,
    "Prerequisites" text,
    "AttackSteps" text NOT NULL,
    "ToolsAndTechniques" text,
    "IndicatorsOfCompromise" text,
    "Impact" integer NOT NULL,
    "Likelihood" integer NOT NULL,
    "RiskLevel" integer NOT NULL,
    "ExistingControls" text,
    "RecommendedMitigations" text,
    "MitreAttackTechnique" character varying(50),
    "MitreAttackTactic" character varying(100),
    "DetectionDifficulty" integer NOT NULL,
    "ResidualRisk" integer NOT NULL,
    "TreatmentStrategy" integer NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ThreatModelId" integer NOT NULL,
    "FindingId" integer,
    "RiskId" integer,
    CONSTRAINT "PK_Attacks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attacks_Findings_FindingId" FOREIGN KEY ("FindingId") REFERENCES "Findings" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Attacks_Risks_RiskId" FOREIGN KEY ("RiskId") REFERENCES "Risks" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Attacks_ThreatModels_ThreatModelId" FOREIGN KEY ("ThreatModelId") REFERENCES "ThreatModels" ("Id") ON DELETE CASCADE
);

-- Create indexes if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Attacks_FindingId') THEN
        CREATE INDEX "IX_Attacks_FindingId" ON "Attacks" ("FindingId");
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Attacks_RiskId') THEN
        CREATE INDEX "IX_Attacks_RiskId" ON "Attacks" ("RiskId");
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Attacks_ThreatModelId') THEN
        CREATE INDEX "IX_Attacks_ThreatModelId" ON "Attacks" ("ThreatModelId");
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_ThreatModels_RiskAssessmentId') THEN
        CREATE INDEX "IX_ThreatModels_RiskAssessmentId" ON "ThreatModels" ("RiskAssessmentId");
    END IF;
END $$;

-- Add missing column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'RiskAcceptanceRequests' AND column_name = 'LinkedRiskAssessmentId') THEN
        ALTER TABLE "RiskAcceptanceRequests" ADD "LinkedRiskAssessmentId" integer;
        CREATE INDEX "IX_RiskAcceptanceRequests_LinkedRiskAssessmentId" ON "RiskAcceptanceRequests" ("LinkedRiskAssessmentId");
        ALTER TABLE "RiskAcceptanceRequests" ADD CONSTRAINT "FK_RiskAcceptanceRequests_RiskAssessments_LinkedRiskAssessment~" FOREIGN KEY ("LinkedRiskAssessmentId") REFERENCES "RiskAssessments" ("Id");
    END IF;
END $$;

-- Mark the migration as applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250731005634_AddThreatModeling', '8.0.18')
ON CONFLICT ("MigrationId") DO NOTHING;