-- SQL script to create ThirdParty table
-- Run this against your PostgreSQL database

CREATE TABLE IF NOT EXISTS "ThirdParties" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Organization" character varying(200) NOT NULL,
    "RepresentativeEmail" character varying(250) NOT NULL,
    "TPRAStatus" integer NOT NULL,
    "RiskLevel" integer NOT NULL,
    "BIARating" integer NOT NULL,
    "TPRAHyperlink" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(100),
    "UpdatedBy" character varying(100),
    CONSTRAINT "PK_ThirdParties" PRIMARY KEY ("Id")
);

-- Add comment to table
COMMENT ON TABLE "ThirdParties" IS 'Third Party Risk Management entity register';