-- Create the ReferenceDataEntries table for smart comboboxes
-- Run this SQL script against your PostgreSQL database

CREATE TABLE IF NOT EXISTS "ReferenceDataEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" integer NOT NULL,
    "Value" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL DEFAULT ,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ModifiedBy" character varying(100),
    "ModifiedAt" timestamp with time zone,
    "UsageCount" integer NOT NULL DEFAULT 0,
    "LastUsedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" character varying(100),
    CONSTRAINT "PK_ReferenceDataEntries" PRIMARY KEY ("Id")
);

-- Create unique index to prevent duplicate values within same category
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReferenceDataEntries_Category_Value" 
ON "ReferenceDataEntries" ("Category", "Value") 
WHERE "IsDeleted" = false;

-- Verify the table was created successfully
SELECT 'ReferenceDataEntries table created successfully' as status;
