CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Department" character varying(100) NOT NULL,
    "JobTitle" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastLoginDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Role" integer NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "BusinessOrganizations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text NOT NULL,
    "ComplianceOwner" text NOT NULL,
    "Stakeholders" text NOT NULL,
    "Type" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BusinessOrganizations" PRIMARY KEY ("Id")
);


CREATE TABLE "ComplianceFrameworks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Version" text NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "UploadedBy" text NOT NULL,
    "UploadedDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ComplianceFrameworks" PRIMARY KEY ("Id")
);


CREATE TABLE "Findings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FindingNumber" text NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Details" character varying(2000) NOT NULL,
    "Impact" integer NOT NULL,
    "Likelihood" integer NOT NULL,
    "Exposure" integer NOT NULL,
    "RiskRating" integer NOT NULL,
    "Status" integer NOT NULL,
    "Owner" character varying(100) NOT NULL,
    "Domain" character varying(100) NOT NULL,
    "BusinessUnit" character varying(100) NOT NULL,
    "BusinessOwner" character varying(100) NOT NULL,
    "OpenDate" timestamp with time zone NOT NULL,
    "SlaDate" timestamp with time zone,
    "Asset" character varying(100) NOT NULL,
    "AssignedTo" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Findings" PRIMARY KEY ("Id")
);


CREATE TABLE "MaturityFrameworks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Version" character varying(50) NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "UploadedBy" character varying(100) NOT NULL,
    "UploadedDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MaturityFrameworks" PRIMARY KEY ("Id")
);


CREATE TABLE "RiskLevelSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "FairCriticalThreshold" numeric NOT NULL,
    "FairHighThreshold" numeric NOT NULL,
    "FairMediumThreshold" numeric NOT NULL,
    "QualitativeCriticalThreshold" numeric NOT NULL,
    "QualitativeHighThreshold" numeric NOT NULL,
    "QualitativeMediumThreshold" numeric NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedBy" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastModifiedBy" text NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RiskLevelSettings" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AssessmentRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequesterName" character varying(100) NOT NULL,
    "Department" character varying(100) NOT NULL,
    "ContactEmail" text NOT NULL,
    "Scope" text NOT NULL,
    "Justification" text NOT NULL,
    "Priority" integer NOT NULL,
    "RequestedTimeline" timestamp with time zone,
    "RequestDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "AssignedToUserId" text,
    "AssignedByUserId" text,
    "AssignmentDate" timestamp with time zone,
    "AssignmentNotes" text NOT NULL,
    "StartedDate" timestamp with time zone,
    "CompletedDate" timestamp with time zone,
    "EstimatedHours" numeric,
    "ActualHours" numeric,
    "AssignedTo" text NOT NULL,
    "Notes" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssessmentRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssessmentRequests_AspNetUsers_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_AssessmentRequests_AspNetUsers_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "AspNetUsers" ("Id")
);


CREATE TABLE "ComplianceAssessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "Assessor" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "CompletedDate" timestamp with time zone,
    "DueDate" timestamp with time zone,
    "CompliancePercentage" numeric NOT NULL,
    "ComplianceFrameworkId" integer NOT NULL,
    "BusinessOrganizationId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ComplianceAssessments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ComplianceAssessments_BusinessOrganizations_BusinessOrganiz~" FOREIGN KEY ("BusinessOrganizationId") REFERENCES "BusinessOrganizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ComplianceAssessments_ComplianceFrameworks_ComplianceFramew~" FOREIGN KEY ("ComplianceFrameworkId") REFERENCES "ComplianceFrameworks" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ComplianceControls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ControlId" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "Priority" integer NOT NULL,
    "ControlText" text NOT NULL,
    "SupplementalGuidance" text NOT NULL,
    "RelatedControls" text NOT NULL,
    "ControlEnhancements" text NOT NULL,
    "ComplianceFrameworkId" integer NOT NULL,
    CONSTRAINT "PK_ComplianceControls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ComplianceControls_ComplianceFrameworks_ComplianceFramework~" FOREIGN KEY ("ComplianceFrameworkId") REFERENCES "ComplianceFrameworks" ("Id") ON DELETE CASCADE
);


CREATE TABLE "FindingClosureRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FindingId" integer NOT NULL,
    "Requester" character varying(100) NOT NULL,
    "ClosureJustification" character varying(2000) NOT NULL,
    "EvidenceLinks" character varying(2000) NOT NULL,
    "AdditionalNotes" character varying(1000) NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "RequestedClosureDate" timestamp with time zone,
    "Status" integer NOT NULL,
    "ReviewedBy" character varying(100) NOT NULL,
    "ReviewDate" timestamp with time zone,
    "ReviewComments" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FindingClosureRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FindingClosureRequests_Findings_FindingId" FOREIGN KEY ("FindingId") REFERENCES "Findings" ("Id") ON DELETE SET NULL
);


CREATE TABLE "RiskAcceptanceRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "BusinessNeed" text NOT NULL,
    "Requester" character varying(100) NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "ReviewDate" timestamp with time zone,
    "ReviewedBy" character varying(100) NOT NULL,
    "ReviewComments" character varying(1000) NOT NULL,
    "RiskSummary" character varying(2000) NOT NULL,
    "CurrentCompensatingControls" character varying(1000) NOT NULL,
    "CurrentInherentRiskRating" integer,
    "CurrentRiskLevelWithControls" integer,
    "TreatmentPlan" character varying(2000) NOT NULL,
    "ProposedCompensatingControls" character varying(1000) NOT NULL,
    "FutureResidualRisk" integer,
    "FutureRiskLevelWithMitigations" integer,
    "CISORecommendation" character varying(2000) NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "FindingId" integer,
    CONSTRAINT "PK_RiskAcceptanceRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RiskAcceptanceRequests_Findings_FindingId" FOREIGN KEY ("FindingId") REFERENCES "Findings" ("Id") ON DELETE SET NULL
);


CREATE TABLE "RiskAssessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Asset" character varying(200) NOT NULL,
    "BusinessUnit" character varying(100) NOT NULL,
    "TechnicalControlsInPlace" text NOT NULL,
    "Description" text NOT NULL,
    "ThreatScenario" text NOT NULL,
    "Status" integer NOT NULL,
    "DateCompleted" timestamp with time zone,
    "Assessor" text NOT NULL,
    "AssessmentType" integer NOT NULL,
    "FindingId" integer,
    "ThreatCommunity" text NOT NULL,
    "ThreatAction" text NOT NULL,
    "ThreatEventFrequency" numeric(18,6) NOT NULL,
    "ContactFrequency" numeric(5,2) NOT NULL,
    "ActionSuccess" numeric(5,2) NOT NULL,
    "LossEventFrequency" numeric(18,6),
    "ProductivityLossMin" numeric(18,2) NOT NULL,
    "ProductivityLossMostLikely" numeric(18,2) NOT NULL,
    "ProductivityLossMax" numeric(18,2) NOT NULL,
    "ResponseCostsMin" numeric(18,2) NOT NULL,
    "ResponseCostsMostLikely" numeric(18,2) NOT NULL,
    "ResponseCostsMax" numeric(18,2) NOT NULL,
    "ReplacementCostMin" numeric(18,2) NOT NULL,
    "ReplacementCostMostLikely" numeric(18,2) NOT NULL,
    "ReplacementCostMax" numeric(18,2) NOT NULL,
    "FinesMin" numeric(18,2) NOT NULL,
    "FinesMostLikely" numeric(18,2) NOT NULL,
    "FinesMax" numeric(18,2) NOT NULL,
    "PrimaryLossMagnitude" numeric(18,2),
    "AnnualLossExpectancy" numeric(18,2),
    "QualitativeLikelihood" integer,
    "QualitativeImpact" integer,
    "QualitativeExposure" integer,
    "QualitativeRiskScore" numeric(5,2),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RiskAssessments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RiskAssessments_Findings_FindingId" FOREIGN KEY ("FindingId") REFERENCES "Findings" ("Id") ON DELETE SET NULL
);


CREATE TABLE "MaturityAssessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "Assessor" character varying(100) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "CompletedDate" timestamp with time zone,
    "DueDate" timestamp with time zone,
    "OverallMaturityScore" numeric NOT NULL,
    "MaturityFrameworkId" integer NOT NULL,
    "BusinessOrganizationId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MaturityAssessments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MaturityAssessments_BusinessOrganizations_BusinessOrganizat~" FOREIGN KEY ("BusinessOrganizationId") REFERENCES "BusinessOrganizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MaturityAssessments_MaturityFrameworks_MaturityFrameworkId" FOREIGN KEY ("MaturityFrameworkId") REFERENCES "MaturityFrameworks" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MaturityControls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ControlId" character varying(100) NOT NULL,
    "Title" character varying(500) NOT NULL,
    "Description" text NOT NULL,
    "Function" character varying(200) NOT NULL,
    "Category" character varying(200) NOT NULL,
    "Subcategory" character varying(200) NOT NULL,
    "ImplementationGuidance" text NOT NULL,
    "HelpText" text NOT NULL,
    "Priority" integer NOT NULL,
    "MaturityFrameworkId" integer NOT NULL,
    CONSTRAINT "PK_MaturityControls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MaturityControls_MaturityFrameworks_MaturityFrameworkId" FOREIGN KEY ("MaturityFrameworkId") REFERENCES "MaturityFrameworks" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ControlAssessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Status" integer NOT NULL,
    "Score" text NOT NULL,
    "EvidenceOfCompliance" text NOT NULL,
    "GapNotes" text NOT NULL,
    "Ownership" text NOT NULL,
    "ProjectedComplianceDate" timestamp with time zone,
    "ProjectNeeded" boolean NOT NULL,
    "TShirtSize" integer,
    "ProjectNumber" text NOT NULL,
    "AssessedBy" text NOT NULL,
    "AssessmentDate" timestamp with time zone,
    "AssignmentParameters" text NOT NULL,
    "SelectionParameters" text NOT NULL,
    "ImplementationNotes" text NOT NULL,
    "TestingProcedures" text NOT NULL,
    "LastTestDate" timestamp with time zone,
    "NextTestDate" timestamp with time zone,
    "ComplianceControlId" integer NOT NULL,
    "ComplianceAssessmentId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Evidence" text NOT NULL,
    "Notes" text NOT NULL,
    CONSTRAINT "PK_ControlAssessments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ControlAssessments_ComplianceAssessments_ComplianceAssessme~" FOREIGN KEY ("ComplianceAssessmentId") REFERENCES "ComplianceAssessments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ControlAssessments_ComplianceControls_ComplianceControlId" FOREIGN KEY ("ComplianceControlId") REFERENCES "ComplianceControls" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Risks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RiskNumber" text NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Asset" character varying(200) NOT NULL,
    "BusinessUnit" character varying(100) NOT NULL,
    "ThreatScenario" text NOT NULL,
    "ALE" numeric(18,2) NOT NULL,
    "RiskLevel" integer NOT NULL,
    "Treatment" integer NOT NULL,
    "Status" integer NOT NULL,
    "Owner" character varying(100) NOT NULL,
    "OpenDate" timestamp with time zone NOT NULL,
    "NextReviewDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "FindingId" integer,
    "RiskAssessmentId" integer,
    CONSTRAINT "PK_Risks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Risks_Findings_FindingId" FOREIGN KEY ("FindingId") REFERENCES "Findings" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Risks_RiskAssessments_RiskAssessmentId" FOREIGN KEY ("RiskAssessmentId") REFERENCES "RiskAssessments" ("Id") ON DELETE SET NULL
);


CREATE TABLE "MaturityControlAssessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CurrentMaturityLevel" integer NOT NULL,
    "TargetMaturityLevel" integer NOT NULL,
    "Evidence" text NOT NULL,
    "GapNotes" text NOT NULL,
    "RecommendedActions" text NOT NULL,
    "Ownership" text NOT NULL,
    "TargetCompletionDate" timestamp with time zone,
    "ProjectNeeded" boolean NOT NULL,
    "TShirtSize" integer,
    "ProjectNumber" character varying(50) NOT NULL,
    "AssessedBy" character varying(100) NOT NULL,
    "AssessmentDate" timestamp with time zone,
    "MaturityControlId" integer NOT NULL,
    "MaturityAssessmentId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MaturityControlAssessments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MaturityControlAssessments_MaturityAssessments_MaturityAsse~" FOREIGN KEY ("MaturityAssessmentId") REFERENCES "MaturityAssessments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MaturityControlAssessments_MaturityControls_MaturityControl~" FOREIGN KEY ("MaturityControlId") REFERENCES "MaturityControls" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_AssessmentRequests_AssignedByUserId" ON "AssessmentRequests" ("AssignedByUserId");


CREATE INDEX "IX_AssessmentRequests_AssignedToUserId" ON "AssessmentRequests" ("AssignedToUserId");


CREATE INDEX "IX_ComplianceAssessments_BusinessOrganizationId" ON "ComplianceAssessments" ("BusinessOrganizationId");


CREATE INDEX "IX_ComplianceAssessments_ComplianceFrameworkId" ON "ComplianceAssessments" ("ComplianceFrameworkId");


CREATE INDEX "IX_ComplianceControls_ComplianceFrameworkId" ON "ComplianceControls" ("ComplianceFrameworkId");


CREATE INDEX "IX_ControlAssessments_ComplianceAssessmentId" ON "ControlAssessments" ("ComplianceAssessmentId");


CREATE INDEX "IX_ControlAssessments_ComplianceControlId" ON "ControlAssessments" ("ComplianceControlId");


CREATE INDEX "IX_FindingClosureRequests_FindingId" ON "FindingClosureRequests" ("FindingId");


CREATE INDEX "IX_MaturityAssessments_BusinessOrganizationId" ON "MaturityAssessments" ("BusinessOrganizationId");


CREATE INDEX "IX_MaturityAssessments_MaturityFrameworkId" ON "MaturityAssessments" ("MaturityFrameworkId");


CREATE INDEX "IX_MaturityControlAssessments_MaturityAssessmentId" ON "MaturityControlAssessments" ("MaturityAssessmentId");


CREATE INDEX "IX_MaturityControlAssessments_MaturityControlId" ON "MaturityControlAssessments" ("MaturityControlId");


CREATE INDEX "IX_MaturityControls_MaturityFrameworkId" ON "MaturityControls" ("MaturityFrameworkId");


CREATE INDEX "IX_RiskAcceptanceRequests_FindingId" ON "RiskAcceptanceRequests" ("FindingId");


CREATE INDEX "IX_RiskAssessments_FindingId" ON "RiskAssessments" ("FindingId");


CREATE INDEX "IX_Risks_FindingId" ON "Risks" ("FindingId");


CREATE INDEX "IX_Risks_RiskAssessmentId" ON "Risks" ("RiskAssessmentId");


