-- Fix Smart Combobox Issue - Create ReferenceDataEntries table and seed data
-- Run this script against your PostgreSQL database

-- Step 1: Create the ReferenceDataEntries table if it doesn't exist
CREATE TABLE IF NOT EXISTS "ReferenceDataEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" integer NOT NULL,
    "Value" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL DEFAULT '',
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ModifiedBy" character varying(100),
    "ModifiedAt" timestamp with time zone,
    "UsageCount" integer NOT NULL DEFAULT 0,
    "LastUsedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" character varying(100),
    CONSTRAINT "PK_ReferenceDataEntries" PRIMARY KEY ("Id")
);

-- Step 2: Create unique index to prevent duplicate values within same category
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReferenceDataEntries_Category_Value" 
ON "ReferenceDataEntries" ("Category", "Value") 
WHERE "IsDeleted" = false;

-- Step 3: Clear any existing test data
DELETE FROM "ReferenceDataEntries" WHERE "CreatedBy" = 'System Migration';

-- Step 4: Insert sample data for all categories

-- Assets (Category = 1)
INSERT INTO "ReferenceDataEntries" ("Category", "Value", "Description", "CreatedBy", "CreatedAt", "IsActive", "IsDeleted", "UsageCount") VALUES 
(1, 'Web Application Server', 'Main web application hosting server', 'System Migration', NOW(), true, false, 0),
(1, 'Database Server', 'Primary database server for application data', 'System Migration', NOW(), true, false, 0),
(1, 'File Server', 'Network file storage server', 'System Migration', NOW(), true, false, 0),
(1, 'Email Server', 'Corporate email server', 'System Migration', NOW(), true, false, 0),
(1, 'Active Directory', 'Domain controller and authentication service', 'System Migration', NOW(), true, false, 0),
(1, 'Customer Portal', 'External customer-facing web portal', 'System Migration', NOW(), true, false, 0),
(1, 'CRM System', 'Customer relationship management system', 'System Migration', NOW(), true, false, 0),
(1, 'ERP System', 'Enterprise resource planning system', 'System Migration', NOW(), true, false, 0),
(1, 'Backup Server', 'Data backup and recovery server', 'System Migration', NOW(), true, false, 0),
(1, 'VPN Gateway', 'Remote access VPN gateway', 'System Migration', NOW(), true, false, 0);

-- Business Owners (Category = 2)
INSERT INTO "ReferenceDataEntries" ("Category", "Value", "Description", "CreatedBy", "CreatedAt", "IsActive", "IsDeleted", "UsageCount") VALUES 
(2, 'John Smith', 'IT Director', 'System Migration', NOW(), true, false, 0),
(2, 'Sarah Johnson', 'Finance Manager', 'System Migration', NOW(), true, false, 0),
(2, 'Mike Brown', 'Operations Manager', 'System Migration', NOW(), true, false, 0),
(2, 'Lisa Davis', 'HR Manager', 'System Migration', NOW(), true, false, 0),
(2, 'Tom Wilson', 'Security Manager', 'System Migration', NOW(), true, false, 0),
(2, 'Emily Chen', 'Compliance Officer', 'System Migration', NOW(), true, false, 0),
(2, 'David Miller', 'VP of Technology', 'System Migration', NOW(), true, false, 0),
(2, 'Jennifer Taylor', 'Customer Service Manager', 'System Migration', NOW(), true, false, 0),
(2, 'Robert Garcia', 'Sales Director', 'System Migration', NOW(), true, false, 0),
(2, 'Amanda White', 'Marketing Manager', 'System Migration', NOW(), true, false, 0);

-- Business Units (Category = 3)
INSERT INTO "ReferenceDataEntries" ("Category", "Value", "Description", "CreatedBy", "CreatedAt", "IsActive", "IsDeleted", "UsageCount") VALUES 
(3, 'Information Technology', 'IT department and infrastructure', 'System Migration', NOW(), true, false, 0),
(3, 'Finance', 'Financial operations and accounting', 'System Migration', NOW(), true, false, 0),
(3, 'Human Resources', 'HR and employee management', 'System Migration', NOW(), true, false, 0),
(3, 'Operations', 'Business operations and logistics', 'System Migration', NOW(), true, false, 0),
(3, 'Sales', 'Sales and business development', 'System Migration', NOW(), true, false, 0),
(3, 'Marketing', 'Marketing and communications', 'System Migration', NOW(), true, false, 0),
(3, 'Customer Service', 'Customer support and service', 'System Migration', NOW(), true, false, 0),
(3, 'Legal', 'Legal and compliance department', 'System Migration', NOW(), true, false, 0),
(3, 'Executive', 'Executive leadership and management', 'System Migration', NOW(), true, false, 0),
(3, 'Research & Development', 'Product development and innovation', 'System Migration', NOW(), true, false, 0);

-- Technical Controls (Category = 4)
INSERT INTO "ReferenceDataEntries" ("Category", "Value", "Description", "CreatedBy", "CreatedAt", "IsActive", "IsDeleted", "UsageCount") VALUES 
(4, 'Firewall Rules', 'Network firewall access control rules', 'System Migration', NOW(), true, false, 0),
(4, 'Antivirus Software', 'Endpoint antivirus and malware protection', 'System Migration', NOW(), true, false, 0),
(4, 'Multi-Factor Authentication', 'MFA for user access control', 'System Migration', NOW(), true, false, 0),
(4, 'Data Encryption', 'Data encryption at rest and in transit', 'System Migration', NOW(), true, false, 0),
(4, 'Access Control Lists', 'File and system access permissions', 'System Migration', NOW(), true, false, 0),
(4, 'Security Monitoring', 'SIEM and security event monitoring', 'System Migration', NOW(), true, false, 0),
(4, 'Patch Management', 'System and software patch management', 'System Migration', NOW(), true, false, 0),
(4, 'Backup and Recovery', 'Data backup and disaster recovery systems', 'System Migration', NOW(), true, false, 0),
(4, 'VPN Access Control', 'Remote access VPN restrictions', 'System Migration', NOW(), true, false, 0),
(4, 'Database Access Controls', 'Database user permissions and roles', 'System Migration', NOW(), true, false, 0),
(4, 'Network Segmentation', 'Network isolation and segmentation', 'System Migration', NOW(), true, false, 0),
(4, 'Intrusion Detection', 'Network and host intrusion detection', 'System Migration', NOW(), true, false, 0),
(4, 'Security Awareness Training', 'Employee security training program', 'System Migration', NOW(), true, false, 0),
(4, 'Vulnerability Scanning', 'Automated vulnerability assessment tools', 'System Migration', NOW(), true, false, 0),
(4, 'Incident Response Plan', 'Security incident response procedures', 'System Migration', NOW(), true, false, 0)
ON CONFLICT ("Category", "Value") WHERE "IsDeleted" = false DO NOTHING;

-- Step 5: Verify the setup worked
SELECT 
    "Category",
    COUNT(*) as "Count",
    CASE "Category"
        WHEN 1 THEN 'Assets'
        WHEN 2 THEN 'Business Owners'
        WHEN 3 THEN 'Business Units'
        WHEN 4 THEN 'Technical Controls'
        ELSE 'Unknown'
    END as "CategoryName"
FROM "ReferenceDataEntries" 
WHERE "CreatedBy" = 'System Migration' AND "IsActive" = true AND "IsDeleted" = false
GROUP BY "Category"
ORDER BY "Category";

-- Final verification - show total count
SELECT COUNT(*) as "TotalReferenceDataEntries" FROM "ReferenceDataEntries" WHERE "IsDeleted" = false;